# Generated by Django 5.2.7 on 2025-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('dis_price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
