# Generated by Django 5.2.7 on 2025-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
