# Generated by Django 6.0.6 on 2026-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_myproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='image',
            field=models.ImageField(default='default.png', upload_to='products/'),
        ),
    ]
